name: Build and Sign APK

on:
  push:
    branches:
      - main

env:
  KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
  KEYALIAS_PASSWORD: ${{ secrets.KEYALIAS_PASSWORD }}
  KEYSTORE_BASE64: ${{ secrets.KEYSTORE_BASE64 }}
  KEY_ALIAS: ${{ secrets.KEY_ALIAS }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v3

    - name: Restore keystore from base64
      run: |
        echo "$KEYSTORE_BASE64" | base64 --decode > release.keystore

    - name: Install system dependencies
      run: |
        sudo apt update
        sudo apt install -y git zip unzip openjdk-17-jdk python3-pip \
          python3-setuptools python3-wheel build-essential libffi-dev libssl-dev \
          libbz2-dev libreadline-dev libsqlite3-dev zlib1g-dev libncurses5 \
          libgdbm-dev liblzma-dev libjpeg-dev libfreetype6-dev libxml2-dev \
          libxmlsec1-dev xz-utils tk-dev adb

    - name: Setup Python and Buildozer
      run: |
        pip install --upgrade pip
        pip install Cython buildozer

    - name: Build signed APK
      run: buildozer android release

    - name: Upload signed APK
      uses: actions/upload-artifact@v3
      with:
        name: signed-apk
        path: bin/*.apk
